name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "ci-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer

jobs:
  build-test:
    name: Build and Test
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Lint
        run: swift format lint -r -p .

      - name: Build
        run: swift build --build-tests

      - name: Test
        run: swift test --skip-build
